version: 2.1

general:
# Uncomment the following to specify only a specific branch
#   branches:
#     only:
#       - dev # specific branch
#       - /dev-.*/ # or regexes
orbs:
  codecov: codecov/codecov@1.0.2
jobs: 
  build:
    machine: true
    working_directory: ~/ci_app
    environment:
      # from https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_install_cli_standalone.htm
      # and https://developer.salesforce.com/media/salesforce-cli/manifest.json
      - DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
    steps:
      - checkout
      - run:
          name: Download CLI
          command: |
            mkdir sfdx
            wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1
      - run:
          name: Install CLI
          command: |
            ./sfdx/install
            sfdx
            mkdir tmp
      - run:
          name: Create hub key
          command: |
            echo 'make hub key'
            #- mkdir keys
            #- echo $HUB_SERVER_KEY_HEX | xxd -r -ps >> keys/hub.key
            openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
            #- openssl rsa -in keys/hub.key -check -noout
          ### Uncomment the following if performing deployments
          #- echo 'make deploy key'
          #- echo $DEPLOY_SERVER_KEY_HEX | xxd -r -ps >> keys/deploy.key
          #- openssl rsa -in keys/deploy.key -check -noout
          #- sfdx force:auth:jwt:grant --clientid $DEPLOY_CONSUMER_KEY --jwtkeyfile keys/deploy.key --username $DEPLOY_SFDC_USER -a deploy
      - run:
          name: Setup Org
          command: |
            echo 'Running tests'
            sfdx force:auth:jwt:grant --clientid $HUB_CONSUMER_KEY --jwtkeyfile assets/server.key --username $HUB_SFDX_USER --setdefaultdevhubusername -a target
            sfdx force:source:deploy -u target -x ./manifest/package.xml
      - run:
          name: Run Apex Tests
          command: |
            mkdir -p ./reports/junit/
            sfdx force:apex:test:run -u target --wait 33 --resultformat junit --codecoverage --testlevel RunLocalTests -d ./reports/junit/
          environment:
            SFDX_IMPROVED_CODE_COVERAGE: true
      - store_artifacts:
          destination: apex-test-results
          path: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - codecov/upload:
          file: coverage/coverage-final.json
          token: 82a54784-4445-4c97-93e8-5fdad31c1eeb

### Uncomment the following if performing deployments
#deployment:
#  override:
#    - sfdx force:source:convert -r force-app -d testDeploy
#    - . cleanupDeploy.sh
#    - sfdx force:mdapi:deploy -d testDeploy/ -u deploy -w 2
